# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unicli < Formula
  desc "Agent-friendly CLI for UniFi Network, Protect, and Access"
  homepage "https://spdg.github.io/unicli/"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SPDG/unicli/releases/download/v0.4.1/unicli_0.4.1_darwin_amd64.tar.gz"
      sha256 "af48fc1ce0f08a35b19c22a867557bd461589e9ee330f5bc3fc3e51905cc0c33"

      define_method(:install) do
        bin.install "unicli"
        bin.install "unicli-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SPDG/unicli/releases/download/v0.4.1/unicli_0.4.1_darwin_arm64.tar.gz"
      sha256 "0fdd9df7d7af8d5ae7b6e60acd47dd40e9406400a0455679d711f4dc6485fb6d"

      define_method(:install) do
        bin.install "unicli"
        bin.install "unicli-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPDG/unicli/releases/download/v0.4.1/unicli_0.4.1_linux_amd64.tar.gz"
      sha256 "af38e0be15da0a862aabf2af07d7c95e1c8bc42ea1b3cbd2728ee1bd0a12e668"
      define_method(:install) do
        bin.install "unicli"
        bin.install "unicli-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SPDG/unicli/releases/download/v0.4.1/unicli_0.4.1_linux_arm64.tar.gz"
      sha256 "0c80149b6594b70a6044dc9f3815c01948804c31d86342e3195fcba3c0837b43"
      define_method(:install) do
        bin.install "unicli"
        bin.install "unicli-mcp"
      end
    end
  end

  test do
    system "#{bin}/unicli", "--version"
  end
end
